"""Shared domain types for the queue-reactive simulator."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Side(str, Enum):
    """Book side or aggressor side."""

    BID = "bid"
    ASK = "ask"

    @property
    def opposite(self) -> "Side":
        return Side.ASK if self is Side.BID else Side.BID


class EventType(str, Enum):
    """Supported order book events."""

    LIMIT = "limit"
    MARKET = "market"
    CANCEL = "cancel"


@dataclass(frozen=True)
class Event:
    """Timestamped event generated by the Markov event engine."""

    timestamp: float
    event_type: EventType
    side: Side
    level: int = 1
    volume: int = 1
    order_id: str | None = None


@dataclass(frozen=True)
class Trade:
    """Execution record produced by marketable flow."""

    timestamp: float
    price: float
    volume: int
    aggressor_side: Side


@dataclass(frozen=True)
class BookSnapshot:
    """Compact state sample used for plots and validation statistics."""

    timestamp: float
    midprice: float
    spread_ticks: int
    bid_depth: int
    ask_depth: int
    imbalance: float
    best_bid: int
    best_ask: int
